### ISSUE TITLE
请教老师能否支持一下这个依赖🙏🙏🙏

### ISSUE THREAD

**Issue by dongyikuan919** [aliyun-idaas/idp4-authenticate-plugin-demo#1]
<dependency>
      <groupId>com.idsmanager.idp</groupId>
      <artifactId>auth-core</artifactId>
      <version>${auth.core.version}</version>
</dependency>

<auth.core.version>4.16.0-mysql</auth.core.version>

**Comment by perryzou** [comment]
您好，我是Perry，已收到你的来信，我会尽快回复。

**Comment by perryzou** [comment]
com.idsmanager.idp.auth-core不对外提供,如需要,请联系所属项目的项目经理单独提供
